<a href="https://colab.research.google.com/github/nikamaishwarya319-cmd/Data-Cleaning-nitflix-Dataset/blob/main/dirty_employee_Ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("dirty-employee.csv")

In [4]:
print(df.head())

   Employee_ID     Full_Name    Age  Gender Joining_Date  \
0          101   Akif Attar    25.0       M     12-02-26
1          102      Ali Khan   30.0    Male    20-Mar-25
2          103   Sara Sheikh    NaN  Female     12-05-20
3          104   Ahmed Patel   -5.0    male    15-Jan-24
4          105   Fatima Noor  180.0       F     10-08-23

               Department   Salary      Country           Phone Marks  \
0                      IT  ?25,000        India      9876543210    85
1  Information Technology  ?30,000  -9876543120      9876543211    90
2                    I.T.  ?28,500        INDIA    (987)6543212    88
3                      HR  ?35,000          ind    987-654-3213    92
4                 Finance  ?40,000       Bharat  +91 9876543214    95

   Unnamed: 10
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

In [5]:
print("Shape:",df.shape)

Shape: (20, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   20 non-null     int64
 1   Full_Name     19 non-null     object
 2   Age           17 non-null     float64
 3   Gender        20 non-null     object
 4   Joining_Date  18 non-null     object
 5   Department    20 non-null     object
 6   Salary        20 non-null     object
 7   Country       20 non-null     object
 8   Phone         19 non-null     object
 9   Marks         19 non-null     object
 10  Unnamed: 10   1 non-null      float64
dtypes: float64(2), int64(1), object(8)
memory usage: 1.8+ KB

In [7]:
df=df.drop_duplicates()

In [8]:
df.isnull().sum()

Employee_ID      0
Full_Name        1
Age              3
Gender           0
Joining_Date     2
Department       0
Salary           0
Country          0
Phone            1
Marks            1
Unnamed: 10     19
dtype: int64

In [9]:
df.drop(columns=['Unnamed: 10'],inplace=True)

In [31]:
df['Age']=pd.to_numeric(df['Age'],errors="coerce")

In [33]:
df['Full_Name']=df['Full_Name'].str.strip()

In [16]:
df['Phone'].fillna('Not Available',inplace=True)

In [20]:
df['Full_Name']=df['Full_Name'].str.strip()

In [21]:
df['Gender']=df['Gender'].str.title().str.strip()

In [34]:
df.dropna(subset=['Joining_Date'],inplace=True)

In [35]:
df['Marks']=pd.to_numeric(df['Marks'],errors='coerce')

In [23]:
df=df[(df['Age']>=18)&(df['Age']<=60)]

In [24]:
df.drop_duplicates(inplace=True)

In [25]:
df['Salary']=df['Salary'].astype(str).str.replace(',','',regex=False)

In [26]:
df['Phone']=df['Phone'].astype(str).str.replace(r'\D','',regex=True)

In [36]:
df.isnull().sum()

Employee_ID     0
Full_Name       0
Age             0
Gender          0
Joining_Date    0
Department      0
Salary          0
Country         0
Phone           0
Marks           1
dtype: int64

In [ ]:
df.to_csv('dirty-employee_cleaned.csv',index=True)